### ISSUE TITLE
Related work: console.createTask

### ISSUE THREAD

**Issue by jkrems** [legendecas/proposal-async-context#11]
This is a new API added to support async stack stitching in DevTools: https://developer.chrome.com/blog/devtools-modern-web-debugging/#linked-stack-traces. API usage example from that page:

```js
function makeScheduler() {
  const tasks = [];

  return {
    schedule(f) {
      const task = console.createTask(f.name);
      tasks.push({ task, f });
    },

    work() {
      while (tasks.length) {
        const { task, f } = tasks.shift();
        task.run(f); // instead of f();
      }
    },
  };
}
```

**Comment by legendecas** [comment]
See https://github.com/legendecas/proposal-async-context/issues/9.

**Comment by jkrems** [comment]
Ah, sorry! Missed that when searching. I think my suggestion here was to mention `console.createTask` in the "Prior Arts" section since the proposal currently doesn't mention this API.

**Comment by jridgewell** [comment]
Yah, that sounds good. I'm actually had a [slide item](https://docs.google.com/presentation/d/1yw4d0ca6v2Z2Vmrnac9E9XJFlC872LDQ4GFR17QdRzk/edit#slide=id.g18e9076879f_0_13) for this in the next presentation.
