### ISSUE TITLE
What does this API do?

### ISSUE THREAD

**Issue by littledan** [legendecas/proposal-async-context#2]
The description of the problem space and priorities in the README is great. For the solution, I see a signature of the classes and some high-level explanation of their role, but it'd be great to also have an explanation of what each of the classes represents in a bit more detail, and what each of the methods do. Right now, it's hard for me to understand.

**Comment by hax** [comment]
I guess the api is same as https://nodejs.org/api/async_hooks.html#async_hooks_class_asynclocalstorage .

**Comment by legendecas** [comment]
Yes, the API is similar to the current implementation in Node.js. I'll update the document text to reflect that, and point out the differences.

**Comment by littledan** [comment]
The current explainer shows this very well. Good work!
