### ISSUE TITLE
Additional work of interest

### ISSUE THREAD

**Issue by rezonant** [legendecas/proposal-async-context#6]
Hello, 

I was directed here by a friend who is also interested in asynchronous observability. I want to note that I also have a draft proposal that touches on the same space, and that you should consider taking the parts you find relevant should they be useful.

The proposal is at https://github.com/rezonant/rezone

It is designed as an elegant replacement for Dominic's zones proposal which got stalled previously. I hope I can help on your proposal to accommodate at least some of the use cases that mine covers. At the very least my proposal provides some additional thoughts that may be insightful or otherwise relevant here.

Best!

**Comment by wh1t3cAt1k** [comment]
My biggest beef with zone.js was the absence of native async/await support. @rezonant does your proposal differ in that regard? 

And, regardless of the answer, is it feasible to work on a Babel transformer that would instrument native async/await calls (as well as other asynchronous APIs like setImmediate, setTimeout etc.) to support at least the async local context - e.g. as an implicit last argument to every method invoked?

(Apologies if I'm not making sense somewhere, my knowledge of the internals of zone.js and transformations is very limited)

**Comment by legendecas** [comment]
Thanks for sharing the ideas! Sorry for not responding earlier.

With the concerns from the committee about the security issues introduced by the surfaced APIs in the language, we decided to proceed with minimal viable APIs necessary to propagate the async contexts.

I'm closing this as the proposal has been updated significantly since then.
