### ISSUE TITLE
Synthetic async tasks

### ISSUE THREAD

**Issue by legendecas** [legendecas/proposal-async-context#9]
A userland API to mark the creation, and scheduling of a synthetic userland async task can help the async contexts to be correctly propagated when the execution flow is multiplexed (i.e. with userland task scheduling). It can potentially mirror the `console.createTask` API [introduced by Chrome](https://developer.chrome.com/blog/devtools-modern-web-debugging/#linked-stack-traces) to track the async stack of the synthetic async task.

Refs: https://github.com/legendecas/proposal-async-context/pull/8

**Comment by littledan** [comment]
To elaborate a bit more here, I think we could use an API similar to [zone.js's wrap](https://github.com/angular/angular/blob/414b1b2d5ffe8eac33749bf472af7eafcf248dba/packages/zone.js/lib/zone.ts#L189), except without reifying the current async context at all: by being a static method on `AsyncContext`.

**Comment by legendecas** [comment]
Introduced `AsyncContext.wrap` to support snapshotting the incumbent value of async contexts in https://github.com/legendecas/proposal-async-context/pull/10.
